name: "CI"

on:
  pull_request:
  push:

jobs:
  unittest:
    uses: na4ma4/actions/.github/workflows/unit-test.yml@v1

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - unittest
    uses: na4ma4/actions/.github/workflows/makefiles-release.yml@dev
    with:
      platforms: 'linux/amd64,windows/amd64'
      language: bare
    # secrets:
    #   token: ${{ secrets.GITHUB_TOKEN }}
